name: Fetch Articles and Deploy

on:
  schedule:
    # Every day at 1AM
    - cron: '0 1 * * *'

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      # Generate articles
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install requests

      - name: Generate articles
        run: python ./utils/fetch_articles.py -o ./public/top_articles.json

      # Commit changes if needed
      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No changes."
          else
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add public/top_articles.json
            git commit -m "Auto-commit: Update articles"
            git push
          fi

      # Build site
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm install
      - run: npm run build

      # Deploy
      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - id: deployment
        uses: actions/deploy-pages@v4